name: tapper
description: Provides extension methods on all types to allow inspection/mutation (tap),
  transformation (pipe), null chaining (zip), and converting (conv)
version: 1.1.0
repository: https://github.com/mcmah309/tapper

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  rust_core: ^1.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
