name: tapper
description: Provides extension methods on all types to allow inspection/mutation (tap),
  transformation (pipe), and converting (conv)
version: 2.0.0
repository: https://github.com/mcmah309/tapper

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  rust: ^3.0.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
