name: tapper
description: Provides extension methods on all types to allow temporary, inspection/mutation (tapping) and
  transformation (piping)
version: 0.1.2
repository: https://github.com/mcmah309/tapper

environment:
  sdk: ^3.2.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  rust_core: ^0.3.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
